type = "card"
title = "荣誉与学术认可"
description = "部分学术、科研与社会实践荣誉。"

[[items]]
title = "第九届清华大学公共管理青年学者论坛入围"
subtitle = "清华大学"
date = "2026"
content = "入围第九届清华大学公共管理青年学者论坛。"

[[items]]
title = "国家级大学生创新训练项目良好结题"
subtitle = "西北农林科技大学"
date = "2024"
content = "担任国家级大学生创新训练项目团队负责人，围绕公共政策、企业意愿、村民参与和乡村文化产业发展开展研究。"

[[items]]
title = "第五届全国大学生城市管理竞赛一等奖"
subtitle = "第三届“智慧治理”公共案例分析大赛"
date = "2023"
content = "作为核心成员参与项目“智慧治理何以能？基层有‘数’，智治有方——基于数‘治’赋能下的宁围治理实践”。"

[[items]]
title = "研究成果入选中国城市管理发展年会"
subtitle = "中国区域科学协会"
date = "2023"
content = "宁围基层数字治理案例研究成果入选2023年中国城市管理发展年会，并进行学术交流展示。"

[[items]]
title = "暑期社会实践优秀调研报告一等奖"
subtitle = "西北农林科技大学"
date = "2023"
content = "调研报告围绕杨凌示范区土地流转政策实施效果，以及农民可持续增收路径展开研究。"

[[items]]
title = "国家级大学生创新训练项目优秀结题"
subtitle = "西北农林科技大学"
date = "2023"
content = "作为核心成员参与政府政策、农户认知与农户参与电商利益联结机制意愿和行为的相关研究。"

[[items]]
title = "百名校园之星——道德之星"
subtitle = "西北农林科技大学"
date = "2023"
content = "获评西北农林科技大学2023年“百名校园之星——道德之星”先进个人。"